/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


  class JSI_EXPORT NativeKeetLinkModuleiOSCxxSpecJSI : public TurboModule {
protected:
  NativeKeetLinkModuleiOSCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

public:
  virtual jsi::Value add(jsi::Runtime &rt, double a, double b) = 0;

};

template <typename T>
class JSI_EXPORT NativeKeetLinkModuleiOSCxxSpec : public TurboModule {
public:
  jsi::Value get(jsi::Runtime &rt, const jsi::PropNameID &propName) override {
    return delegate_.get(rt, propName);
  }

  static constexpr std::string_view kModuleName = "RNKeetLink";

protected:
  NativeKeetLinkModuleiOSCxxSpec(std::shared_ptr<CallInvoker> jsInvoker)
    : TurboModule(std::string{NativeKeetLinkModuleiOSCxxSpec::kModuleName}, jsInvoker),
      delegate_(reinterpret_cast<T*>(this), jsInvoker) {}

private:
  class Delegate : public NativeKeetLinkModuleiOSCxxSpecJSI {
  public:
    Delegate(T *instance, std::shared_ptr<CallInvoker> jsInvoker) :
      NativeKeetLinkModuleiOSCxxSpecJSI(std::move(jsInvoker)), instance_(instance) {}

    jsi::Value add(jsi::Runtime &rt, double a, double b) override {
      static_assert(
          bridging::getParameterCount(&T::add) == 3,
          "Expected add(...) to have 3 parameters");

      return bridging::callFromJs<jsi::Value>(
          rt, &T::add, jsInvoker_, instance_, std::move(a), std::move(b));
    }

  private:
    T *instance_;
  };

  Delegate delegate_;
};

} // namespace facebook::react
