/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "rnkeetlinkJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeKeetLinkModuleiOSCxxSpecJSI_add(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeKeetLinkModuleiOSCxxSpecJSI *>(&turboModule)->add(
    rt,
    args[0].asNumber(),
    args[1].asNumber()
  );
}

NativeKeetLinkModuleiOSCxxSpecJSI::NativeKeetLinkModuleiOSCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("RNKeetLink", jsInvoker) {
  methodMap_["add"] = MethodMetadata {2, __hostFunction_NativeKeetLinkModuleiOSCxxSpecJSI_add};
}


} // namespace facebook::react
